# docker-compose up -d
# docker-compose down
version: "3.9"
services:
  backend:
    container_name: schedusmart-backend-container
    build: 
      context: ./schedusmart-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  frontend:
    container_name: schedusmart-frontend-container
    build:
      context: ./schedusmart-backend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
